# **Python For Neuro Week 6**: More Numpy and Pandas

## Warmup

We're going to start today by loading in ```mat_1.npy``` again. If you don't remember how to do this, use google to find the right function to use. Please assign the array to variable called ```arr```.

In [106]:
import numpy as np

In [107]:
# load in data
arr = np.load('ex_array.npy')
arr

array([[[[1.06735651e-01, 8.50013428e-01, 6.61261976e-02, ...,
          1.22214287e+00, 1.85433810e+00, 2.97715561e-02],
         [1.74584281e+00, 1.04634545e+00, 1.19461252e+00, ...,
          3.86994751e-01, 1.46257796e-01, 5.57668861e-01],
         [1.27660851e+00, 1.63782002e+00, 1.73077654e+00, ...,
          2.69178437e-01, 8.87518742e-01, 4.97409664e-01],
         ...,
         [1.33977689e-01, 1.61987886e-01, 4.46480597e-01, ...,
          4.39952432e-01, 6.42594250e-01, 1.23527806e+00],
         [2.47564259e+00, 1.69413446e+00, 2.12417460e+00, ...,
          2.61901093e+00, 3.11246504e+00, 1.92026681e+00],
         [7.29644202e-01, 2.04679777e+00, 1.37959358e+00, ...,
          1.74199210e+00, 2.11039000e+00, 8.98703266e-01]],

        [[8.10785116e-01, 9.33062418e-01, 2.59379116e-01, ...,
          1.31543734e+00, 1.29622586e+00, 1.23752785e+00],
         [5.66745857e-01, 7.88732871e-01, 1.09353632e+00, ...,
          4.95212124e-01, 2.18896547e-01, 5.55039361e-01],
        

In [108]:
arr.shape # structure: (Conditions x Trials x Neurons x Times)

(2, 10, 50, 2000)

## Summary operations

Summary operations allow you to collapse an array according to a certain summary statistic. For instance, we may want to compute the overall mean firing rate in our experimental data:

In [109]:
arr.mean()

np.float64(0.8717270073789575)

You can also specify the axis along we want to average. For instance, maybe we want to average firing rates across individual trials:

In [110]:
arr.shape # dimensions of the array

(2, 10, 50, 2000)

In [111]:
arr_across_trials = arr.mean(axis=1) # averages across 10 different buckets

In [112]:
arr_across_trials.shape 

(2, 50, 2000)

The `keepdims` argument means that you don't remove the dimensions you're averaging over, but rather set their length to 1:

In [113]:
arr_across_trials = arr.mean(axis=1, keepdims=True)

In [114]:
arr_across_trials.shape

(2, 1, 50, 2000)

You can average across multiple axes as well. For instance, maybe you want to average across both trials and time:

In [115]:
arr_across_trials_and_time = arr.mean(axis=(1,3))

In [116]:
arr_across_trials_and_time.shape

(2, 50)

### Question 1

- What is the average firing rate across all neurons, times, and trials for each condition?
- (Advanced.) Subtract the average firing rate per time across all neurons, trials, and conditions from the original array.

In [117]:
avg_condition = arr.mean(axis=(1,2,3))
avg_condition # should be 2 values

array([0.98828779, 0.75516623])

In [118]:
avg_overall = arr.mean(axis=3, keepdims=True) # keep number of dimensions (for avg firing rate per time) so that they are the same shape
avg_overall.shape

(2, 10, 50, 1)

In [119]:
arr - avg_overall

array([[[[-7.00688590e-01,  4.25891874e-02, -7.41298043e-01, ...,
           4.14718632e-01,  1.04691386e+00, -7.77652685e-01],
         [ 1.00568119e+00,  3.06183827e-01,  4.54450893e-01, ...,
          -3.53166873e-01, -5.93903828e-01, -1.82492763e-01],
         [ 4.59796796e-01,  8.21008307e-01,  9.13964819e-01, ...,
          -5.47633280e-01,  7.07070254e-02, -3.19402053e-01],
         ...,
         [-3.41114426e-01, -3.13104230e-01, -2.86115189e-02, ...,
          -3.51396840e-02,  1.67502135e-01,  7.60185947e-01],
         [ 1.13938081e-01, -6.67570042e-01, -2.37529908e-01, ...,
           2.57306423e-01,  7.50760531e-01, -4.41437690e-01],
         [-5.57690268e-01,  7.59463299e-01,  9.22591078e-02, ...,
           4.54657628e-01,  8.23055532e-01, -3.88631203e-01]],

        [[ 4.15208163e-02,  1.63798119e-01, -5.09885184e-01, ...,
           5.46173041e-01,  5.26961558e-01,  4.68263548e-01],
         [-1.61982306e-01,  6.00047083e-02,  3.64808156e-01, ...,
          -2.33516039e

## Indexing

Indexing in vectors works just as in lists:

In [120]:
vec_1 = np.array([1,2,3])
vec_1

array([1, 2, 3])

In [121]:
vec_1[0]

np.int64(1)

For matrices and higher-dimensional arrays, a single index selects a single row:

In [122]:
mat_1 = np.array(([1,2,3],[4,5,6]))
mat_1

array([[1, 2, 3],
       [4, 5, 6]])

In [123]:
mat_1[0]

array([1, 2, 3])

In [124]:
mat_1[0][1] # accesses the 2nd element of the 1st row

np.int64(2)

Instead of using two brackets, you can also separate the row and column index by a comma:

In [125]:
# The following two lines of code are equivalent
print(mat_1[0][0])
print(mat_1[0,0])

1
1


### Slicing

Slicing is a useful way of extracting more than one element. In particular, `j:k` extracts the elements j,...,k-1:

In [126]:
vec = np.arange(10)
print(vec)

[0 1 2 3 4 5 6 7 8 9]


In [127]:
vec[3:7]

array([3, 4, 5, 6])

We can leave either end of the range away and it will default to the beginning and the end of the list, respectively.

In [128]:
vec[:7]

array([0, 1, 2, 3, 4, 5, 6])

In [129]:
vec[3:]

array([3, 4, 5, 6, 7, 8, 9])

In [130]:
vec[:] # What do you think this will do?

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

You can therefore also use the colon to select all rows of a matrix and specific columns.

In [131]:
mat_1

array([[1, 2, 3],
       [4, 5, 6]])

In [132]:
mat_1[:,0]

array([1, 4])

You can add another colon to specify a step size, similarly to how you would use these three arguments in `range`.

In [133]:
vec[3:7:2] # '2' specifies step size

array([3, 5])

We could still leave away the beginning or the end of the slice:

In [134]:
vec[::2]

array([0, 2, 4, 6, 8])

### Question 2
Predict the output of the following commands:

In [135]:
vec[:4] # 0,1,2,3

array([0, 1, 2, 3])

In [136]:
vec[5:9:2] # 5,7

array([5, 7])

In [137]:
vec[:7:2] # 0, 2, 4, 6

array([0, 2, 4, 6])

In [138]:
vec[2::2] # 2,4,6,8

array([2, 4, 6, 8])

### Boolean indexing

Do you remember how to create an array that is true if and only if `vec` is smaller than 5?

In [139]:
vec = np.arange(10)
vec

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [140]:
selector = vec <= 5
selector

array([ True,  True,  True,  True,  True,  True, False, False, False,
       False])

You can use these boolean arrays to subset the corresponding true values.

In [141]:
vec

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [142]:
vec[selector]

array([0, 1, 2, 3, 4, 5])

In [143]:
vec[vec<=5]

array([0, 1, 2, 3, 4, 5])

You can do the same with matrices:

In [144]:
mat_1 = np.array([[1, 2],
       [3, 4],
       [5, 6]])

In [145]:
mat_1 >= 3 # "mask" array

array([[False, False],
       [ True,  True],
       [ True,  True]])

In [146]:
mat_1[mat_1 >= 3]

array([3, 4, 5, 6])

### Questions 3
- Consider the example matrix from above and subset all entries with values between 2 and 4. You can try to do this in one line or do it through multiple lines!

In [147]:
mat_1[(mat_1 >= 2) & (mat_1 <= 4)]

array([2, 3, 4])

# Pandas
## Python's package for handling data
### Motivation for pandas
Dictionaries allow us to save multiple attributes of a particular object. For example, we can store some information about a lesson:

In [148]:
lesson_5 = {
    'topic': 'Numpy',
    'teacher': 'Sharon',
    'week': 5
}

Often, we collect multiple observations for which we record the same attributes and we'd like to store them together:

In [149]:
lesson_3 = {
    'topic': 'Basics of Python 2',
    'teacher': 'Sharon',
    'week': 3
}
lesson_1 = {
    'topic': 'Setting up Python',
    'teacher': 'Abhi',
    'week': 1
}

We could go about this by storing them in a list:

In [150]:
lst_lessons = [lesson_5, lesson_3, lesson_1]

In [151]:
lst_lessons

[{'topic': 'Numpy', 'teacher': 'Sharon', 'week': 5},
 {'topic': 'Basics of Python 2', 'teacher': 'Sharon', 'week': 3},
 {'topic': 'Setting up Python', 'teacher': 'Abhi', 'week': 1}]

However, such lists are lacking a lot of functionality. For example, we may want to print out only those observations where Jasmine was the teacher. We'd have to use a for loop for this:

In [152]:
sharons_lessons = [
    lesson for lesson in lst_lessons if lesson['teacher'] == 'Sharon'
]
sharons_lessons

[{'topic': 'Numpy', 'teacher': 'Sharon', 'week': 5},
 {'topic': 'Basics of Python 2', 'teacher': 'Sharon', 'week': 3}]

We therefore need a new data structure that can record multiple pieces of information about multiple observations. This is provided by `pandas` (which stands for *panel data*):

In [153]:
#We normally import pandas like this
import pandas as pd

The core object in pandas is a *data frame*, which consists of observations organized along its rows and different pieces of information about its observations organized along its columns.

In [154]:
df_lessons = pd.DataFrame(lst_lessons)
df_lessons

topic teacher  week
0               Numpy  Sharon     5
1  Basics of Python 2  Sharon     3
2   Setting up Python    Abhi     1

### Finding out basic information

In [155]:
df_lessons.shape

(3, 3)

In [156]:
df_lessons.columns

Index(['topic', 'teacher', 'week'], dtype='object')

### Indexing

Regular brackets return a specific column or a subset of columns:

In [157]:
df_lessons['teacher']

0    Sharon
1    Sharon
2      Abhi
Name: teacher, dtype: object

(*Note:* The object that is returned is called a `pd.Series` and has a few additional features compared to a one-dimensional numpy array. I personally don't use those additional features and think they are counter-productive, but you can look them up if you have to interact with them.)

You can operate on those columns in the same way you would operate on numpy arrays:

In [158]:
df_lessons['teacher'] == 'Sharon'

0     True
1     True
2    False
Name: teacher, dtype: bool

In [159]:
df_lessons[['topic', 'teacher']]

topic teacher
0               Numpy  Sharon
1  Basics of Python 2  Sharon
2   Setting up Python    Abhi

`.loc` allows you to index data frames by row numbers and column names:

In [160]:
df_lessons.loc[1, 'teacher']

'Sharon'

This also works with slicing:

In [161]:
df_lessons.loc[1:, 'teacher']

1    Sharon
2      Abhi
Name: teacher, dtype: object

In [162]:
df_lessons.loc[:, ['topic', 'teacher']]

topic teacher
0               Numpy  Sharon
1  Basics of Python 2  Sharon
2   Setting up Python    Abhi

`iloc` works in the same way, but allows you to access columns according to their numerical index rather than their name:

In [163]:
df_lessons.iloc[1, 1]

'Sharon'

Finally you can also do boolean indexing with rectangular brackets.

In [164]:
selector = df_lessons['teacher'] == 'Sharon' # select all rows where Sharon is the teacher
df_lessons[selector] # return all rows where Sharon is the teacher

topic teacher  week
0               Numpy  Sharon     5
1  Basics of Python 2  Sharon     3

(Note that the single `=` assigns the command to the right of it to the variable on its left. The double `==` on the other hand compares the values in `df_lessons['teacher']` and determines whether they are equal to `'Jasmine'`.)

In [165]:
df_lessons[df_lessons['teacher']=='Sharon']

topic teacher  week
0               Numpy  Sharon     5
1  Basics of Python 2  Sharon     3

Finally, you can add new columns in the same way you would add a new key, value pair to a dictionary:

In [166]:
df_lessons

topic teacher  week
0               Numpy  Sharon     5
1  Basics of Python 2  Sharon     3
2   Setting up Python    Abhi     1

In [167]:
df_lessons['homework'] = [True, True, False]

In [168]:
df_lessons

topic teacher  week  homework
0               Numpy  Sharon     5      True
1  Basics of Python 2  Sharon     3      True
2   Setting up Python    Abhi     1     False

### Exercises
1. Create a data frame that additionally includes this week (week 6) with the appropriate topic (pandas) and teacher (Sam).
2. Print out the topic for the second row.
3. Subset the data frame to only print out the lessons for week 3 and higher.
4. Create a new data frame that also includes week 7's lesson with teacher Sam. However, you don't know the topic yet. How does `pandas` represent this information? (Hint: Create a dictionary that only contains the keys `week` and `teacher`, but not `topic`. Try adding it to the list we used above and turning it into a dataframe.)
5. You could have alternately also represented this information as a two-dimensional array with observations structured along rows and variables structured along columns. What would the difference be and why might this be a bad idea in this case? Discuss with the other students at your table.

In [169]:
#1 - my response
new_row = pd.DataFrame({'topic': 'pandas', 'teacher': 'Sam', 'week': 6, 'homework': False},
                       index=[0])
df_lessons = pd.concat([df_lessons, new_row], ignore_index=True)
df_lessons

topic teacher  week  homework
0               Numpy  Sharon     5      True
1  Basics of Python 2  Sharon     3      True
2   Setting up Python    Abhi     1     False
3              pandas     Sam     6     False

In [170]:
#1 - class response
wk6_dict = {
    'topic': 'Pandas',
    'teacher': 'Abhi',
    'week': 6
}

df = lst_lessons.append(wk6_dict)
df = pd.DataFrame(lst_lessons)
df

topic teacher  week
0               Numpy  Sharon     5
1  Basics of Python 2  Sharon     3
2   Setting up Python    Abhi     1
3              Pandas    Abhi     6

In [171]:
df_lessons.loc[3] = wk6_dict
df_lessons

/var/folders/xt/qs85nkk57c508r2jh9123qlh0000gn/T/ipykernel_27141/2802310168.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'nan' has dtype incompatible with bool, please explicitly cast to a compatible dtype first.
  df_lessons.loc[3] = wk6_dict


topic teacher  week homework
0               Numpy  Sharon     5     True
1  Basics of Python 2  Sharon     3     True
2   Setting up Python    Abhi     1    False
3              Pandas    Abhi     6      NaN

In [172]:
#2
df.loc[1,'topic']
df['topic'][1]
df.iloc[1,0]

'Basics of Python 2'

In [173]:
#3
df[df['week']>=3]

topic teacher  week
0               Numpy  Sharon     5
1  Basics of Python 2  Sharon     3
3              Pandas    Abhi     6

In [174]:
#4
wk7_dict = {
    'teacher': 'Sam',
    'week': 7
}

lst_lessons.append(wk7_dict)
df2 = pd.DataFrame(lst_lessons)

In [175]:
df2

topic teacher  week
0               Numpy  Sharon     5
1  Basics of Python 2  Sharon     3
2   Setting up Python    Abhi     1
3              Pandas    Abhi     6
4                 NaN     Sam     7

### Saving and loading a data frame
You can save data frames in different formats. A popular format is csv (comma-separated values), which represents each observation in one row and each variable separated by commas.

In [176]:
df_lessons.to_csv('df_lessons.csv')

Let's inspect this file.

We'll be using csv files today. Note that they are not always ideal. For example, they do not save the type of your different values which can lead to issues. The hdf5 format is a popular alternative (but a little more complicated to use); alternatively the feather format is lightweight and more reliable, but a little less common.

In [ ]:
df_lessons_loaded = pd.read_csv('df_lessons.csv')

In [ ]:
df_lessons_loaded

### Exercises
1. Read in the file `dot_motion.csv` using pandas and assign it to the variable `df_dm`.
2. Try exploring the file and describe the data contained in it.
3. Subset the data frame to only contain the observations with a reaction time of above 100.
4. Create a new variable 'accuracy' that is 1 if the motion and the choice are matching and 0 otherwise.

#### Hint for 4:
If the motion and choice are matching, their entries should be equal. Create an array `accuracy` that contains as a boolean whether they are or are not matching. You can turn this boolean array (with True and False value) into a float array (which will assign 1 to True and 0 to False), using `accuracy.astype(float)`.
