# PfN Homework: Week 5

We're going to begin by reviewing some of the ways we can create arrays using numpy's inbuilt functions:

In [2]:
import numpy as np

Let's begin with ```linspace```, which allows us to evenly tile an array with elements from start to finish. We specify the number of steps the function should take. For example, try to predict what the following code will output:

In [3]:
arr = np.linspace(0, 10, 5)
arr

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

What if you want to specify the step *size* instead? Then we can use a complementary function,  ```arange```. Try to guess what ```arr``` will be once again, and then run the code to check whether you were correct.

In [4]:
arr = np.arange(0, 10, 2.5)
arr

array([0. , 2.5, 5. , 7.5])

It's often useful to also create arrays that consist of the same element. For instance, we can use ```ones``` to create a numpy array of - wait for it - ones. Note here that we're creating a multidimensional array.

In [5]:
arr = np.ones((3, 4, 2)) # 3 blocks (each with 4 rows, 2 columns)
arr

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

We can also do more fancy things, like create an identity matrix using ```eye```:


In [6]:
arr = np.eye(4)
arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

Let's practice creating arrays below:

## Question 1:
A) Create a numpy array using ```linspace``` that counts up from 3 to 8 in steps of 0.5.

B) Create the same array, but use ```arange```

C) Using the wonders of the world wide web, please figure out how to create an array of all zeros. Make the array 3x4x5.

In [11]:
#1A
my_arr = np.linspace(3,8,11)
my_arr

array([3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. , 7.5, 8. ])

In [15]:
#1B
my_arr = np.arange(3,8.5,0.5)
my_arr

array([3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. , 7.5, 8. ])

In [18]:
#1C
zeros_arr = np.zeros((3,4,5))
zeros_arr

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

# Putting arrays together

What if we want to put arrays together? With lists this is easy: you just add them together. But, as we discussed during class, the whole point of numpy arrays is that when we add them we ... add them. Luckily, as usual, numpy has a function for that.

Let's begin with the simplest example, putting two arrays together:

In [21]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

#Note that the arrays are provided here as a tuple ... this will be important later
c = np.concatenate((a, b))
c

array([1, 2, 3, 4, 5, 6])

What if we want to put three arrays together? You can just provide more arrays to the tuple that is given to ```concatenate```.

In [22]:
d = np.concatenate((a, b, c))
d

array([1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6])

What if we want to put arrays together, over and over again? We can use ```np.tile```

In [23]:
np.tile(a, 3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

You can also use ```tile``` to stack arrays on top of each other. Here, we're telling the function to repeat array ```a``` three times, in one column.

In [24]:
np.tile(a, (3,1))

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

Can you predict what the following code would output?

In [25]:
np.tile(a, (3,2))

array([[1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3]])

There are a ton of other functions that you can use to put arrays together, which you can use flexibly to solve the next few problems. Use the numpy documentation and a bit of googling to find the appropriate functions. As you'll see, there will be multiple ways to solve the same problem!

# Question 2

A) Write a function that takes in a 1D array for input and returns the same array, mirrored, stacked N times, where N is also an input to the function. For instance, given the array ```[1,2,3] ```as an input, and ```N=2```, the function would return ```[[1,2,3,3,2,1], [1,2,3,3,2,1]]```

B) Write another function that takes in a 1D array for input and returns another array, with each element repeated N times. For example, given ```[1,2,3]``` and ```N=3``` the function would return ```[1,1,1,2,2,2,3,3,3]```


In [56]:
#2A
def mirror_array(array, N):
    reverse = np.flip(array) # reverses the list (such that the first element goes first and the first element goes last)
    mirror = np.concatenate((array, reverse))
    stack = np.tile(mirror, (N,1))
    return stack

# testing the function
arr = np. array([1,2,3])
mirror_array(arr,2)
    

array([[1, 2, 3, 3, 2, 1],
       [1, 2, 3, 3, 2, 1]])

In [62]:
#2B
def repindel(array, N):
    repeated_arr = np.repeat(array, N)
    return repeated_arr

# testing the function
arr = np.array([1,2,3])
repindel(arr,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])